[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mlc"
version = "0.1"
description = "Machine Learning Compiler"

[project.scripts]
mlc = "mlc.main:main_cli"
